Implement keyboardDidHide listener and open modal if the Keyboard appears
Expensify/react-native-picker-select pull request #10
Opened 2023-04-12 13:28 UTC by OlimpiaZurek

Original issue: $https://github.com/Expensify/App/issues/16353

This PR changes implementation on Keyboard dismiss inside `togglePicker` method.  In current implementation `Keyboard.dismiss()` is called immediately, which can caused issues ( eg.  https://github.com/Expensify/App/issues/16353). 
I added listener `keyboardDidHide` and open modal if the Keyboard appears. Otherwise just open modal.

2023-04-12 13:51 UTC, 0xmiroslav commented
@danieldoglas when user currently focuses on input and select picker and close picker, should we focus back to original input?

2023-04-12 14:41 UTC, danieldoglas commented
@0xmiroslav I don't think we should go back to the original input, we should just close.

I'm addressing internally why I can't assign you to this PR, I think we have some permission issues here. Will get back to you soon.

2023-04-12 14:58 UTC, danieldoglas commented
@0xmiroslav can you try to review this PR without me assigning you?

2023-04-12 15:11 UTC, 0xmiroslav commented
> @0xmiroslav can you try to review this PR without me assigning you?

Sure thing

2023-04-14 16:48 UTC, 0xmiroslav requested changes
Code mostly looks good. Just minor feedback:

2023-04-14 16:48 UTC, 0xmiroslav commented on src/index.js
> +               this.updatePickerState(animate,postToggleCallback);
```suggestion
               this.updatePickerState(animate, postToggleCallback);
```

2023-04-14 16:48 UTC, 0xmiroslav commented on src/index.js
> +            this.updatePickerState(animate,postToggleCallback);
```suggestion
            this.updatePickerState(animate, postToggleCallback);
```

2023-04-14 16:48 UTC, 0xmiroslav commented on src/index.js
> +        else {
```suggestion
        } else {
```

2023-04-17 07:39 UTC, OlimpiaZurek commented
all comments have already been resolved

2023-04-17 09:33 UTC, 0xmiroslav commented
@OlimpiaZurek please pull from master and fix lint. Not related to this PR but asking since you also worked on https://github.com/Expensify/react-native-picker-select/pull/9.

```diff
- const preserveSpaces = (label) =>  {
+ const preserveSpaces = (label) => {
    return label.replace(/ /g, '\u00a0');
-  }
+ }
```

And it would be good to add some automated tests.

2023-04-17 12:52 UTC, OlimpiaZurek commented
> @OlimpiaZurek please pull from master and fix lint. Not related to this PR but asking since you also worked on #9.
> 
> ```diff
> - const preserveSpaces = (label) =>  {
> + const preserveSpaces = (label) => {
>     return label.replace(/ /g, '\u00a0');
> -  }
> + }
> ```
> 
> And it would be good to add some automated tests.

done

2023-04-17 15:45 UTC, 0xmiroslav approved these changes
Looks good, tests well, automated tests pass.
Checklist will be done in app PR.
cc: @danieldoglas

2023-04-17 18:05 UTC, danieldoglas approved these changes

2023-04-17 18:07 UTC, merged