Expose the focusRef reference
Expensify/react-native-picker-select pull request #6
Opened 2023-03-22 23:44 UTC by cubuspl42

2023-03-22 23:51 UTC, cubuspl42 commented on src/index.js
> +        focusRef: PropTypes.oneOfType([
I picked a custom name for the ref, as forwarding the real ref broke literally [the whole testsuite](https://github.com/Expensify/react-native-picker-select/blob/84ee97dec11c2e65609511eb5a757d61bbeeab79/test/test.js#L98). It's all built on the assumption that the `ref` actually points to the actual `RNPickerSelect` component.

2023-03-23 14:26 UTC, parasharrajat requested changes
we have to only fix text input ref forwarding as it overwrites the internal ref prop.

2023-03-23 14:26 UTC, parasharrajat commented on src/index.js
> +        ]),
```suggestion
```

Not needed.

2023-03-23 14:26 UTC, parasharrajat commented on src/index.js
> +        focusRef: undefined,
```suggestion
```

2023-03-23 14:26 UTC, parasharrajat commented on src/index.js
> +}
```suggestion
```

2023-03-23 14:26 UTC, parasharrajat commented on src/index.js
> +                    ref={this.props.focusRef}
```suggestion
```

I didn't understand this duplicate ref assignment.

2023-03-23 14:26 UTC, parasharrajat commented on src/index.js
> +                    ref={this.props.focusRef}
```suggestion
```

2023-03-23 14:26 UTC, parasharrajat commented on src/index.js
> +                    }}
```suggestion
                    ref={(el) => {
                        this.setInputRef(el);
                        
                        if(!textInputProps.ref){
                           return;
                        } 
                        
                        if(typeof textInputProps.ref === 'function'){
                         textInputProps.ref(el);
                        }else{
                        textInputProps.ref.current = el;
                        }
                    }}
```

2023-03-23 14:26 UTC, parasharrajat commented
Please add a description to the PR. Explain Why are we doing these changes?

2023-03-23 15:56 UTC, cubuspl42 commented on src/index.js
> +}
I don't really understand why inlining this function improves readability. This is basic DRY.

```
      if(typeof textInputProps.ref === 'function'){
       textInputProps.ref(el);
      }else{
      textInputProps.ref.current = el;
      }
```

In practice, such code is more prone to mistakes and requires extra brain power to ensure that all three `textInputProps.ref` are indeed the same expression.

2023-03-23 16:00 UTC, jakub-trzebiatowski commented on src/index.js
> +        ]),
Of course I understand your suggestion to drop an extra ref property (`focusRef`; but name is not crucial) and rely on `pickerProps.ref` / `textInputProps.ref`.

But it has consequences, right? In the bigger picture, you actually mean that it would be better to do our own platform switching on top of `react-native-picker-select/picker`. Do I understand that correctly?

```js
if (Platform.OS == 'web') {
  return <RNPicker pickerProps={{ref: /* ... */}} /* ... */ />;
} else {
  return <RNPicker textInputProps={{ref: /* ... */}} /* ... */ />;
}
```

...or something among that lines.

Unless I'm missing something.

I decided to put changes here, as I'm pretty sure that that's what author of the approach had in mind. But the extra switch on the app-side is also totally fine for me.

2023-03-23 16:08 UTC, cubuspl42 commented on src/index.js
> +        ]),
@parasharrajat [Relevant thread](https://github.com/Expensify/App/pull/16433/files#r1146432817) on the use-site

2023-03-23 16:14 UTC, parasharrajat commented on src/index.js
> +}
> This is basic DRY

It is unnecessary to put it inside a function if it is only used once.  Also, it does not seem to serve a big difference. Inline code is more readable.

2023-03-23 16:17 UTC, cubuspl42 commented on src/index.js
> +}
I don't agree neither with the first (i.e that functions are only for things used more than once) nor with the second

But I assume that your word here is final; I'll inline

2023-03-23 16:20 UTC, jakub-trzebiatowski commented on src/index.js
> +                    ref={this.props.focusRef}
It's not duplicate, it's another approach where `RNPickerSelect` is controlling the refs and they aren't overridable. But I already understand that you disagree with this approach.

It all comes down to [this thread](https://github.com/Expensify/react-native-picker-select/pull/6#pullrequestreview-1354740078)

2023-03-23 16:22 UTC, parasharrajat commented on src/index.js
> +        ]),
I don't think there are any consequences here. Allowing to pass ref's through two ways is confusing.  I think it is hard to argue the philosophy of the lib but we can just do minimal changes that are required for us or a blocker for us. You could be right to use `focusref` logic and it could be serving a better purpose.

the main blocker for us is the overwriting ref for TextInput. we don't have to extend this to the focus concept that is only relevant in our App.

2023-03-23 16:23 UTC, cubuspl42 commented on src/index.js
> +        ]),
Okey, I can see we're in agreement; I will adjust both sides of this solution

2023-03-23 16:31 UTC, parasharrajat commented on src/index.js
> +}
No, my word is not final. This is a no-blocker for me. But we can at least put the function at the top. ESLint will throw `Function used before is defined`...

2023-03-23 16:32 UTC, parasharrajat commented on src/index.js
> +                    ref={this.props.focusRef}
I am thinking that we should do minimal changes first.

2023-03-23 16:37 UTC, parasharrajat commented
Please do not force push. we don't prefer force pushes. Also, commits needs to be GPG signed.

2023-03-23 16:50 UTC, cubuspl42 commented
> Please do not force push. we don't prefer force pushes.

That means that every typo, discarded idea or non-working approach lands in the repository? 😶 That's unusual.

I forced pushed to undo the force push.

I'll figure out the GPG signing.

2023-03-23 16:53 UTC, cubuspl42 commented on src/index.js
> +}
I already followed your suggestion, so there's no need to jump back and forth. But I appreciate that you were open to my perspective.

2023-03-23 17:27 UTC, cubuspl42 commented
@parasharrajat One last force push, because otherwise I couldn't add GPG signing

2023-03-23 17:45 UTC, jakub-trzebiatowski commented on src/index.js
> +        focusRef: PropTypes.oneOfType([
Outdated

2023-03-25 17:44 UTC, parasharrajat approved these changes
LGTM. I will ask someone to merge it when I have tested the original PR.

2023-04-20 20:15 UTC, parasharrajat commented
@cubuspl42 We can close this PR.

2023-04-20 22:50 UTC, closed without merging